### PR TITLE
added unit tests, fixed logic errors

### LINKED ISSUE #18: Add unit tests to views
There are currently no unit tests for any views, add them.

### PR DESCRIPTION
**Pull request by trescube**
Fixed #18 

Added unit tests for all views, including negative tests.

Additionally, 3 views had logic errors that were causing unintended behavior in parameter validation.  For example:

```
if( !vs.isset('popularity:field') ||
    !vs.isset('popularity:modifier'), // , used when || was intended
    !vs.isset('popularity:max_boost') ){
  return null;
}
```

The effect of the above behavior is that the conditional would only succeed when `!vs.isset('popularity:max_boost')` evaluated to true.  When a list of statements is separated by a `,`, all statements are executed but only the last is used for the outer expression evaluation.  See https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Comma_Operator

### CODE REVIEW

File: view/admin.js [hunk 1]
```diff
@@ -17,8 +17,8 @@ module.exports = function( property ){
     }
 
     // base view
-    var view = { "match": {} };
-    
+    var view = { 'match': {} };
```
Comment (orangejulius) [inline view/admin.js:20]: Every time I see a line change like this I think back to my PHP days, where using single quotes was apparently an Important Performance Improvement. I'm glad now it's just a linter preference

**Comment by orangejulius** [comment]
Looks like #21 contains this, but :+1: either way
